### ISSUE TITLE
Publish minor release

### ISSUE THREAD

**Issue by burodepeper** [puranjayjain/language-liquid#13]
Hey @puranjayjain,

If you are happy with the changes I've made (`package.json` is updated automatically by `apm`, that's why I reverted it to 0.4) then I'll leave the first `apm publish minor` up to you. It will probably take some time for the PR on `language-gfm` to go through, but in the meantime you can focus on the remaining issues here.

**Comment by puranjayjain** [comment]
resolved in latest release
