### ISSUE TITLE
Disabling .html

### ISSUE THREAD

**Issue by chriswelchgb** [puranjayjain/language-liquid#16]
In my project I only have .liquid files with liquid, and .html are strictly HTML5. By default, all new HTML files open with language-liquid. This is only a problem because I want to use atom-htmlhint, but it will only work when the HTML files are parsed with the HTML language type.

Can you provide a configuration to allow me to only have parsing supported in .liquid?

**Comment by puranjayjain** [comment]
@chriswelchgb in issue #10 we were trying to solve the problem of embedding language inside one another. I think it would solve this problem too but unfortunately I cant get it to work right now. I'll have dive a little deeper into the api and some time. Meanwhile Feel free to start a PR.

**Comment by chriswelchgb** [comment]
Thanks for the quick response!
