### ISSUE TITLE
Support for Whitespace Control

### ISSUE THREAD

**Issue by rickydazla** [puranjayjain/language-liquid#20]
Shopify introduced some new syntax to control whitespace in rendered Liquid docs: 
https://help.shopify.com/themes/liquid/basics/whitespace e.g. 

```html
{%- comment -%}
  {{- someVariable -}}
{%- endcomment -%}
```

**Comment by rickydazla** [comment]
@puranjayjain I would make a PR but my regex skills are poor! Note that they say _"If you don't want any of your tags to output whitespace, as a general rule you can add hyphens to both sides of all your tags ({%- and -%}):"_ — so, I guess in the snippets it would be nice if they expanded with these as standard. What do you think?

**Comment by puranjayjain** [comment]
Go ahead give it a shot. Yes I agree there should a mechanism for that. More and more languages are supporting whitespace control so it should be in built
