### ISSUE TITLE
Duplicate key 'sort' in snippets/language-liquid.cson

### ISSUE THREAD

**Issue by raphinesse** [puranjayjain/language-liquid#38]
Using v0.6.0 of this package in Atom 1.26.0-beta0. On startup, I get the following error:

**Failed to load snippets from '~/.atom/packages/language-liquid/snippets/language-liquid.cson'**
`~/.atom/packages/language-liquid/snippets/language-liquid.cson: Duplicate key 'sort'`

**Comment by astramare** [comment]
The same problem with 1.25.0 version.

**Comment by niedfelj** [comment]
@puranjayjain Are you managing this project or not? This code doesn't load in Atom anymore

**Comment by lizbanach** [comment]
I have the same issue.

**Comment by sixcupsofcoffee** [comment]
Syntax highlighting still works, it's just the snippets file that won't load.

I submitted a pull request to fix this, but I don't know if it'll ever get merged if @puranjayjain has become inactive. The branch to fix it is [here](https://github.com/SixCupsofCoffee/language-liquid/tree/fix-duplicate-sort-key), you just need to manually install it in ~/.atom/packages/

**Comment by puranjayjain** [comment]
@niedfelj  @erbanach  @sixcupsofcoffee  I have not been active on Github lately. But will try my best to get this resolved asap.

**Comment by Ya7yaL** [comment]
I have the same issue on same Atom build. I get this error message :

```
Failed to load snippets from '/Users/yann/.atom/packages/language-liquid/snippets/language-liquid.cson'
/Users/yann/.atom/packages/language-liquid/snippets/language-liquid.cson: Duplicate key 'sort'
```

**Comment by sixcupsofcoffee** [comment]
There is a (temporary, possibly) fix merged in here, but @puranjayjain needs to update the version here so Atom will trigger an update. You can also download this repo and install it to Atom manually.

**Comment by Ya7yaL** [comment]
Thank you @sixcupsofcoffee, I pasted the master repo in ~/.atom/packages , no more error.

**Comment by jmsfwk** [comment]
This is fixed in master but the new version need to be published.

**Comment by vaevictis** [comment]
I've just updated the file manually. Not ideal for long term, but for now, it got rid of the alert box each time I'd load atom.

**Comment by sixcupsofcoffee** [comment]
Yeah, the version hasn’t been updated yet on here so it won’t trigger an update in Atom.

**Comment by flaviocamilo** [comment]
A tip to automatically install from the master branch (so you don't have to clone and move): `apm i puranjayjain/language-liquid`.

**Comment by ileitch** [comment]
@puranjayjain can you tag 0.6.1 please so that this can be resolved? Thank you 😃

**Comment by puranjayjain** [comment]
I apologize for the delay, Will do it tonight

**Comment by ashfame** [comment]
@puranjayjain Gentle Reminder! Please tag 0.6.1 :)

**Comment by jlgabriel** [comment]
Another vote for the update to 0.6.1, thanks for the Atom package!

**Comment by bl4ck5un** [comment]
same issue here. would be great to see a fix.

**Comment by michaelmyc** [comment]
Voting for the update to 0.6.1! Thanks!

**Comment by puranjayjain** [comment]
Bumped to 0.7.0 to accommodate multiple fixes 🍻 🎉 🎈
