### ISSUE TITLE
HTML Element within Capture breaking syntax highlighting

### ISSUE THREAD

**Issue by reggi** [puranjayjain/language-liquid#6]
The following is breaking the syntax highlighting:

```
{% capture test %}
<p>Hello</p>
{% endcapture %}
```

![screen shot 2015-05-16 at 5 31 34 pm](https://cloud.githubusercontent.com/assets/296798/7668048/72aff5c8-fbf1-11e4-9531-f0549589be59.png)

**Comment by puranjayjain** [comment]
@reggi sorry for a late reply recently took up the mantle so if you are still facing the problem can you give a reply? a yes or no would suffice

**Comment by reggi** [comment]
Looks good now. Free to close.
