### ISSUE TITLE
Atom doesn't recognize .html files using liquid syntax

### ISSUE THREAD

**Issue by mattmischuk** [puranjayjain/language-liquid#8]
I've been using Siteleaf which allows .html files to have liquid syntax within them. However Atom doesn't auto detect the syntax automatically.

**Comment by liquidvisual** [comment]
I just stumbled onto the same problem.

**Comment by cbracco** [comment]
@kieranmasterton is there anyway for an atom project to automatically detect liquid syntax for .html files ([something like this](https://github.com/benjohnson/atom-django-templates#default-grammar), perhaps)?
